name: 'canary-bounce'
description: 'bounce the deployments'
author: 'test'
branding:
  icon: 'cloud'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  kubeconfig: 
    description: 'base64 encoded .kube/config'
